import { getBestTradeHighlightLabel } from "@/lib/analytics/insight-thresholds"
import type { WeeklyDebriefResult } from "@/lib/ai/weekly-debrief-types"
import { formatPnL } from "@/lib/trade-utils"

export function formatWeeklyDebriefReport(debrief: WeeklyDebriefResult): string {
  const { summary, commentary, grades, recommendations } = debrief
  const lines: string[] = [
    "VYRONIS AI — WEEKLY TRADER DEBRIEF",
    debrief.weekLabel,
    "",
    "SUMMARY",
    `Trades: ${summary.tradeCount}`,
    `Total P&L: ${formatPnL(summary.totalPnL, summary.totalPnL >= 0 ? "WIN" : "LOSS")}`,
    `Win Rate: ${summary.winRate}%`,
    `Best Setup: ${summary.bestSetup || "—"}`,
    `Worst Setup: ${summary.worstSetup || "—"}`,
    `Best Session: ${summary.bestSession || "—"}`,
    `Worst Emotional State: ${summary.worstEmotionalState || "—"}`,
    `Discipline Trend: ${summary.disciplineTrend}${summary.disciplineTrendDelta ? ` (${summary.disciplineTrendDelta > 0 ? "+" : ""}${summary.disciplineTrendDelta})` : ""}`,
    `Average Quality Score: ${summary.averageQualityScore ?? "—"}`,
    `Most Repeated Mistake: ${summary.mostRepeatedMistake || "—"}`,
    "",
    "WEEKLY GRADES",
    `Discipline: ${grades.discipline} (${grades.disciplineScore}/100)`,
    `Execution: ${grades.execution} (${grades.executionScore}/100)`,
    `Psychology: ${grades.psychology} (${grades.psychologyScore}/100)`,
    `Risk Management: ${grades.riskManagement} (${grades.riskManagementScore}/100)`,
    `Overall Trader Grade: ${grades.overall} (${grades.overallScore}/100)`,
    "",
    "AI COMMENTARY",
  ]

  if (commentary.improved.length > 0) {
    lines.push("What improved:")
    commentary.improved.forEach((item) => lines.push(`- ${item}`))
  }
  if (commentary.declined.length > 0) {
    lines.push("What declined:")
    commentary.declined.forEach((item) => lines.push(`- ${item}`))
  }
  if (commentary.emotionalObservations.length > 0) {
    lines.push("Emotional observations:")
    commentary.emotionalObservations.forEach((item) => lines.push(`- ${item}`))
  }
  if (commentary.executionProblems.length > 0) {
    lines.push("Execution problems:")
    commentary.executionProblems.forEach((item) => lines.push(`- ${item}`))
  }
  if (commentary.strongestHabits.length > 0) {
    lines.push("Strongest habits:")
    commentary.strongestHabits.forEach((item) => lines.push(`- ${item}`))
  }
  if (commentary.dangerousPatterns.length > 0) {
    lines.push("Dangerous patterns:")
    commentary.dangerousPatterns.forEach((item) => lines.push(`- ${item}`))
  }

  lines.push("", "RECOMMENDATIONS")
  recommendations.forEach((item) => lines.push(`- ${item}`))

  if (debrief.journalLinks.bestTrade) {
    const label = getBestTradeHighlightLabel(
      debrief.journalLinks.bestTrade.result,
      debrief.journalLinks.bestTrade.pnl,
    )
    lines.push(
      "",
      `${label}: ${debrief.journalLinks.bestTrade.pair} (${debrief.journalLinks.bestTrade.result})`,
    )
  }
  if (debrief.journalLinks.worstTrade) {
    lines.push(
      `Worst trade: ${debrief.journalLinks.worstTrade.pair} (${debrief.journalLinks.worstTrade.result})`,
    )
  }

  lines.push("", "Generated by Vyronis HQ")
  return lines.join("\n")
}

export async function copyWeeklyDebriefReport(debrief: WeeklyDebriefResult): Promise<void> {
  const report = formatWeeklyDebriefReport(debrief)
  if (typeof navigator !== "undefined" && navigator.clipboard?.writeText) {
    await navigator.clipboard.writeText(report)
    return
  }
  throw new Error("Clipboard unavailable")
}

export function printWeeklyDebriefReport(debrief: WeeklyDebriefResult): void {
  const report = formatWeeklyDebriefReport(debrief)
  const printWindow = window.open("", "_blank", "noopener,noreferrer,width=900,height=1000")
  if (!printWindow) {
    throw new Error("Popup blocked — allow popups to export PDF")
  }

  printWindow.document.write(`
    <!DOCTYPE html>
    <html>
      <head>
        <title>Vyronis HQ Weekly Debrief</title>
        <style>
          body { font-family: ui-sans-serif, system-ui, sans-serif; padding: 32px; color: #111; line-height: 1.5; }
          h1 { font-size: 20px; margin-bottom: 4px; }
          pre { white-space: pre-wrap; font-size: 13px; }
        </style>
      </head>
      <body>
        <h1>Vyronis HQ Weekly Debrief</h1>
        <pre>${report.replace(/</g, "&lt;")}</pre>
      </body>
    </html>
  `)
  printWindow.document.close()
  printWindow.focus()
  printWindow.print()
}
